name: Deploy Demo Time

on:
  push: 
    paths:
      - 'apps/demo-time/**'

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy app version configured in versions file
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Determine app version to deploy 
        run: |
          cat apps/demo-time/version >> $GITHUB_ENV

      - name: Configured application version for deployment
        run: |
          echo "${{ env.APP_VERSION }}" 

      - name: Get Package 
        run: ./get-app-jar.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: deploy to production with artifact
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ vars.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: ${{ env.AZURE_SPRING  }}
          app-name: demo-time
          use-staging-deployment: true
          create-new-deployment: true
          package: demo-time-${{ env.APP_VERSION }}.jar
      
      - name: set production deployment step
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: set-production
          service-name: ${{ env.AZURE_SPRING  }}
          app-name: demo-time
          use-staging-deployment: true

      - name: get active deployment name
        id: retrive_deployment_name
        run: |
          echo "DEPLOYMENT_NAME=$(az spring app show -s ${{ env.AZURE_SPRING }} -g ${{env.AZURE_RG}} -n demo-time --query properties.activeDeployment.name -o tsv)" >> $GITHUB_ENV
          echo "LOCATION=$(az spring show -n ${{ env.AZURE_SPRING }}  -g ${{env.AZURE_RG}} --query location -o tsv)" >> $GITHUB_ENV
            
      - name: Apply ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: ./armtemplate/template.json
          parameters: service_name=${{ env.AZURE_SPRING }} app_name=demo-time deployment_name=${{env.DEPLOYMENT_NAME}} location=${{env.LOCATION}} 
